[project]
name = "project-cyclic"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "docker>=7.1.0",
    "litellm>=1.80.5",
    "loguru>=0.7.3",
    "python-dotenv>=1.2.1",
    "typer[all]>=0.20.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.6",
]
